import Purchase from "../../models/Purchase.js";
import Supplier from "../../models/supplier.js";

// @desc    Get all purchases for a specific supplier
// @route   GET /api/purchases/supplier/:supplierId
// @access  Private/Admin
export const getSupplierPurchases = async (req, res) => {
  try {
    const purchases = await Purchase.find({ supplier: req.params.supplierId }).sort({ supplyDate: -1 });
    res.status(200).json({ success: true, data: purchases });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Create a new purchase/supply record
// @route   POST /api/purchases
// @access  Private/Admin
export const createPurchase = async (req, res) => {
  try {
    // Get purchase data from frontend request
    const { supplier: supplierId, productName, quantity, unitPrice, sellingPrice, discount, cost, paidAmount, supplyDate } = req.body;
    
    const supplier = await Supplier.findById(supplierId);
    if (!supplier) {
      return res.status(404).json({ success: false, message: "Supplier not found" });
    }

    // Profit validation
    const disc = parseFloat(discount) || 0;
    const sPrice = parseFloat(sellingPrice) || 0;
    const uPrice = parseFloat(unitPrice) || 0;
    const finalSellingPrice = sPrice * (1 - disc / 100);
    
    if (finalSellingPrice < uPrice) {
      return res.status(400).json({ 
        success: false, 
        message: `Invalid discount! Final selling price (Rs. ${finalSellingPrice.toFixed(2)}) cannot be lower than cost price (Rs. ${uPrice.toFixed(2)}).` 
      });
    }

    // Convert total cost to number
    let remainingCost = parseFloat(cost);
    // Store how much credit was used
    let appliedCredit = 0;


    // Apply existing credit balance from previous overpayments
    if (supplier.creditBalance > 0) {
      appliedCredit = Math.min(supplier.creditBalance, remainingCost);
      remainingCost -= appliedCredit;
      supplier.creditBalance -= appliedCredit;
    }


    // Convert paid amount to number
    // If empty use 0
    let actualPaid = parseFloat(paidAmount) || 0;
    let balance = 0;

    // If customer paid more than remaining cost
    if (actualPaid > remainingCost) {
      // Overpayment: add excess to credit balance
      const excess = actualPaid - remainingCost;
      supplier.creditBalance += excess;
      balance = 0;
    } else {
      balance = remainingCost - actualPaid;
    }

    const purchase = await Purchase.create({
      supplier: supplierId,
      productName,
      quantity,
      unitPrice,
      sellingPrice,
      discount: disc,
      cost,
      paidAmount: actualPaid,
      appliedCredit,
      balance,
      supplyDate,
      paymentHistory: actualPaid > 0 ? [{ amount: actualPaid, date: supplyDate || Date.now() }] : []
    });

    await supplier.save();

    res.status(201).json({ success: true, data: purchase });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Update a purchase payment
// @route   PUT /api/purchases/:id
// @access  Private/Admin
export const updatePurchase = async (req, res) => {
  try {
    const { productName, quantity, unitPrice, sellingPrice, discount, paidAmount } = req.body;
    const purchase = await Purchase.findById(req.params.id);
    if (!purchase) {
      return res.status(404).json({ success: false, message: "Record not found" });
    }

    // Find supplier related to purchase
    const supplier = await Supplier.findById(purchase.supplier);
    if (!supplier) {
      return res.status(404).json({ success: false, message: "Supplier not found" });
    }

    // 1. Revert previous financial effects of this specific purchase on the supplier credit
    // Put back applied credit
    supplier.creditBalance += (purchase.appliedCredit || 0);
    
    // Revert any credit generated by a previous overpayment on THIS purchase
    const requiredOutOfPocket = purchase.cost - (purchase.appliedCredit || 0);
    if (purchase.paidAmount > requiredOutOfPocket) {
        const excess = purchase.paidAmount - requiredOutOfPocket;
        supplier.creditBalance -= excess;
    }

    // 2. Update purchase details
    if (productName) purchase.productName = productName;
    if (quantity !== undefined) purchase.quantity = parseFloat(quantity);
    if (unitPrice !== undefined) purchase.unitPrice = parseFloat(unitPrice);
    if (sellingPrice !== undefined) purchase.sellingPrice = parseFloat(sellingPrice);
    if (discount !== undefined) purchase.discount = parseFloat(discount);

    // Re-validate profit on update
    const finalSPrice = purchase.sellingPrice * (1 - (purchase.discount || 0) / 100);
    if (finalSPrice < purchase.unitPrice) {
        return res.status(400).json({ 
            success: false, 
            message: `Update failed! Final selling price (Rs. ${finalSPrice.toFixed(2)}) would be lower than cost price (Rs. ${purchase.unitPrice.toFixed(2)}).` 
        });
    }
    
    // Recalculate total cost
    purchase.cost = purchase.quantity * purchase.unitPrice;

    // Optional: update paid amount if provided
    if (paidAmount !== undefined) {
      purchase.paidAmount = parseFloat(paidAmount);
    }

    // 3. Apply the NEW financial logic
    let currentRemainingCost = purchase.cost;
    let newAppliedCredit = 0;

    // Use available credit first
    if (supplier.creditBalance > 0) {
      newAppliedCredit = Math.min(supplier.creditBalance, currentRemainingCost);
      currentRemainingCost -= newAppliedCredit;
      supplier.creditBalance -= newAppliedCredit;
    }

    let newBalance = 0;
    if (purchase.paidAmount > currentRemainingCost) {
      // Overpayment becomes credit
      const excess = purchase.paidAmount - currentRemainingCost;
      supplier.creditBalance += excess;
      newBalance = 0;
    } else {
      newBalance = currentRemainingCost - purchase.paidAmount;
    }

    purchase.appliedCredit = newAppliedCredit;
    purchase.balance = newBalance;

    await purchase.save();
    await supplier.save();

    res.status(200).json({ success: true, data: purchase });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Delete a purchase record
// @route   DELETE /api/purchases/:id
// @access  Private/Admin
export const deletePurchase = async (req, res) => {
  try {
    const purchase = await Purchase.findById(req.params.id);
    if (!purchase) {
      return res.status(404).json({ success: false, message: "Record not found" });
    }

    const supplier = await Supplier.findById(purchase.supplier);
    if (supplier) {
        // Restore the credits
        supplier.creditBalance += (purchase.appliedCredit || 0);
        
        //requre cost to pay without remaining cost
        const remainingCostAtTime = purchase.cost - (purchase.appliedCredit || 0);
         // Check if overpayment existed and calculate excess
        if (purchase.paidAmount > remainingCostAtTime) {
            const excess = purchase.paidAmount - remainingCostAtTime;
            supplier.creditBalance -= excess;
        }
        await supplier.save();
    }

    await purchase.deleteOne();
    res.status(200).json({ success: true, message: "Record deleted" });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Add a payment installment
// @route   POST /api/purchases/:id/payments
// @access  Private/Admin
export const addPayment = async (req, res) => {
  try {
    const { amount } = req.body;
    const purchase = await Purchase.findById(req.params.id);
    if (!purchase) {
      return res.status(404).json({ success: false, message: "Record not found" });
    }

    const supplier = await Supplier.findById(purchase.supplier);
    if (!supplier) {
      return res.status(404).json({ success: false, message: "Supplier not found" });
    }

    const installmentAmount = parseFloat(amount);
    if (isNaN(installmentAmount) || installmentAmount <= 0) {
      return res.status(400).json({ success: false, message: "Invalid payment amount" });
    }

    // Update purchase totals
    purchase.paidAmount += installmentAmount;
    
    // Recalculate balance and potential overpayment (credit)
    const totalPayable = purchase.cost - (purchase.appliedCredit || 0);
    
    if (purchase.paidAmount > totalPayable) {
      const excess = purchase.paidAmount - totalPayable;
      supplier.creditBalance += excess;
      purchase.balance = 0;
    } else {
      purchase.balance = totalPayable - purchase.paidAmount;
    }

    // Add to history
    purchase.paymentHistory.push({
      amount: installmentAmount,
      date: Date.now()
    });

    await purchase.save();
    await supplier.save();

    res.status(200).json({ success: true, data: purchase });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};